.gitignore
.npmignore
CHANGELOG.md
package.json
rollup.config.js
src/esri-loader.ts
tsconfig.json

use rollup to create umd build w/ global ('esriLoader')
move source to src folder and rename to esri-loader
added CHANGELOG
resolves #11 (I hope)

default export and  outputs es5/umd (main) and es5/esm (module)

---

src/esri-loader.ts
test/esri-loader.spec.js

Currently the `isLoaded()` function is only checking if the `require` function existed.  This is causing an issue when using the `esri-loader` module in Electron because this ends up getting evaluated on a process running in NodeJS and therefor the API for `require` is different.  By adding a check for if the `esri-loader` script has been loaded if pushes this evaluation into the browser and Electron no longer throws an error.

check is esri-loader script has been loaded

---

CHANGELOG.md
src/esri-loader.ts
test/esri-loader.spec.js

handle script load errors

---

CHANGELOG.md
src/esri-loader.ts

resolves #64
I've confirmed that this fixes the issue by running npm-linked in a server-rendered app as  @tgeorges suggested here: https://github.com/Esri/esri-loader/issues/64#issuecomment-353637373

fix window undefined error in server-rendered apps

---

CHANGELOG.md
src/esri-loader.ts
test/esri-loader.spec.js

resolves #61 
resolves #51
I made these changes a while back. I actually had [originally tried using a singleton promise](https://github.com/Esri/esri-loader/compare/8dc3b0219c99c3c6d4291ba9dbe3a5e245b42274...fix/singleton-promise) instead of holding onto `_currentUrl` like I do in this PR. However, I ended up having to expose that singleton promise (as `esriLoader._loadModulesPromise`) so that I could clear the state between tests. I didn't like that, so I started on the approach in this PR.
TBH I couldn't get the tests to pass in this branch either so I just dropped it and planned to revisit it in a couple of days. Those days turned into weeks, and I just revisited it today, [removed one line from the test spec](https://github.com/Esri/esri-loader/compare/fix/current-url?expand=1#diff-24 …

fallback to current url when loading modules

---

CHANGELOG.md
package.json
src/esri-loader.ts

found useful to load the default css stylesheet automatically

added automatically loading the default esri's css stylesheet

---

CHANGELOG.md
src/esri-loader.ts
test/esri-loader.spec.js

`loadScript()` now takes a `css` option that is a URL (string) and (if present) passes that to `loadCss()` to load a stylesheet by URL
- Is there an example or test page to demonstrate any new or changed features?
not yet
- Does your PR include appropriate tests for source code alterations?
yes
- If you're adding or changing a public API, did you update the docs Usage sections of the README? If not, please provide a code snippet that demonstrates how to consume the new or updated API(s).
not yet. Basically, it's either `loadScript({ css: cssUrl })` or `loadModules(['esri/map'], { css: cssUrl })`, but it seems like it's going to be tricky to figure out how that fits into the README, and I may have had too much 🍷to deal w/ that at this hour.
- Provide a …

`loadScript()` takes a `css` option to load stylesheet by URL

---

README.md
src/esri-loader.ts
test/esri-loader.spec.js

A simple search and replace addressing this issue: https://github.com/Esri/esri-loader/issues/104
I updated the `DEFAULT_URL` and also the README.
`npm run test` passes 100%.

update ArcGIS API version 4.6 -> 4.7 and 3.23 -> 3.24

---

README.md

This PR adds a link to an example of using Dojo Loader with Dojo 2+ (4 is coming out shortly!). Let me know if you have any questions.

Add Dojo 2+ example to README examples

---

README.md

- `README` updates mainly centered around code snippets using ES2015 import statements.
- `https` where possible in links.
- Added a couple missing entries in the TOC.
- Some markdownlint rules were also applied throughout.
- Potential remaining work?
> Maybe add a discrete ES5/CDN example that shows how to use the global.
- #136

136-readme-updates

---

CHANGELOG.md
README.md
package.json
src/esri-loader.ts
src/utils/css.ts
test/esri-loader.spec.js

`insertCssBefore` option lets user insert esri css before _any_ node (like a `<style>`) using a selector instead of just the nth `<link`> element. Also `loadCss` takes this as a second argument instead of overloading the first, which will be an easier API to work with as we tackle issues like #157 
This is not a breaking change b/c we haven't released #158 yet
- Is there an example or test page to demonstrate any new or changed features?
no
- Does your PR include appropriate tests for source code alterations?
yes
- If you're adding or changing a public API, did you update the docs Usage sections of the README?
~~not yet, still thinking about how/when to doc this~~ yes!
#107

insertCssBefore option to insert esri css before any node using a selector

---

CHANGELOG.md
src/esri-loader.ts

When I moved code into modules, I forgot to re-export the ILoadScriptOptions interface. This fixes that.
- Is there an example or test page to demonstrate any new or changed features?
no
- Does your PR include appropriate tests for source code alterations?
no
- If you're adding or changing a public API, did you update the docs Usage sections of the README?
n/a
resolves #166

export missing ILoadScriptOptions

---

src/utils/index.ts

In node environments (when esri-loader is used in a SSR app), Node throws the following error:
```sh
ReferenceError: window is not defined
```
Adding back the correct `typeof` check from a previous commit that did not fail: https://github.com/Esri/esri-loader/commit/3145419df900b9713e65ae77f56f2dded30f7dd2#diff-2cfb1554a9cbe2bf7981031a26f82e4eL5

Fix window undefined in Node environments

---

.travis.yml
src/modules.ts

This PR uses generics to avoid the need for explicit type casting when using `loadModules`.
```ts
type MapModules = [typeof import("esri/map"), typeof import("esri/geometry/Extent")];
// Current typings require explicit type casting.
const [Map, Extent] = await (loadModules(["esri/map", "esri/geometry/Extent"], options) as Promise<MapModules>);
// Using generics to specify module types.
const [Map, Extent] = await loadModules<MapModules>(["esri/map", "esri/geometry/Extent"], options);
```

Added generics for `loadModules` typings improvements.

---

README.md

The main part of this PR is adding the new section to the README. It also adds a link to the FAQ issues as well as fixes some spelling mistakes.
I'm not sure if this is exactly what you were looking for in #150, but I wanted to contribute back to this project in some way. I basically took the amazing words of wisdom from @tomwayson in #71 & #124 and tweaked it to make it fit within the context of the README.
Thanks for the great project!

Add "Using Classes Synchronously" section to README

---

README.md
src/utils/css.test.ts
src/utils/url.ts

Add support for using the [next](https://github.com/Esri/feedback-js-api-next) version of the Esri JS API.
This almost certainly has conflicts with #187 but I wanted to keep them separate. I'm happy to resolve them if the maintainers approve of both PRs. I could resubmit a new PR with both or add one to the other.

add support for "next" version

---

README.md
src/script.test.ts
src/utils/css.test.ts
src/utils/url.test.ts
src/utils/url.ts

Updated all code & Readme to ArcGIS JavaScript API v4.14 & v3.31.

Update to ArcGIS JavaScript API v4.14/3.31

---

README.md
src/script.test.ts
src/utils/css.test.ts
src/utils/url.test.ts
src/utils/url.ts

Updates: https://www.esri.com/arcgis-blog/products/js-api-arcgis/announcements/whats-new-in-arcgis-api-for-javascript-april-2020/
This PR updates the default version:
- v4.14 => v4.15
- v3.31 => 3.32

Update to ArcGIS JavaScript API v4.15/3.32

---

README.md
src/script.test.ts
src/utils/css.test.ts
src/utils/url.test.ts
src/utils/url.ts

Updates: https://www.esri.com/arcgis-blog/products/js-api-arcgis/announcements/whats-new-in-the-arcgis-api-for-javascript-july-2020/
This PR updates the default version:
- v4.15 => v4.16
- v3.32 => 3.33

Update to ArcGIS JavaScript API v4.16/3.33

---

README.md

I added a quick summary of using the [esri-loader-typings-helper plugin](https://marketplace.visualstudio.com/items?itemName=CalebMackey.esri-loader-typings-helper) for VS Code as mentioned in #266.  This was a documentation only update to the `README.md`.  As per @tomwayson's instructions, I added this in the [Advanced Usage](https://github.com/Esri/esri-loader#advanced-usage) portion where I included it as part of the TypeScript support. 
I kept it short and sweet as I did not want to distract too much from the regular documentation.  Please let me know if you want me to add more, less, or alter what I proposed in this PR.  Thanks!

Added docs for `esri-loader-typings-helper` plugin for VS Code

---

README.md
src/script.test.ts
src/utils/css.test.ts
src/utils/url.test.ts
src/utils/url.ts

hi @tomwayson, @jwasilgeo 
Here is my commit to upgrade the default version of JSAPI from 4.18 to 4.19.
Thanks,
Jinnan

default to ArcGIS API for JavaScript version 4.19

---

CHANGELOG.md
README.md
archived-examples.md
src/esri-loader.ts
src/modules.ts
src/script.test.ts
src/script.ts
src/utils/css.test.ts
src/utils/css.ts
src/utils/index.ts
src/utils/url.test.ts
src/utils/url.ts

Proposed updates:
- default to JS API 4.25; update docs w/ latest version numbers - @andygup
- raise visibility of deprecation notice for frameworks that do not support async/await at runtime, e.g. Angular because of Zone.js limitations
- archive framework samples and various 3.x-related sections to archived-examples.md. Most of the samples haven't been updated` in years
- moved an old 4.x Types codepen to the archive that was written at 4.10 (Retired) it also included other outdated deps
cc @odoe

Update to 4.25 and 3.42

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.md
README.md
archived-examples.md
package.json
src/modules.ts
src/script.test.ts
src/script.ts
src/utils/css.ts

This PR replaces all instances of the old naming convention with the new name. It roughly follows a convention of using the full name once per section followed by just using shorthand "SDK" or "API" where appropriate. The plan is to merge this PR next week, on/around Dec 14.
For more information see the [Introducing the ArcGIS Map SDKs](https://www.esri.com/arcgis-blog/products/developers/announcements/introducing-the-arcgis-maps-sdks/) blog post. 
Items of note:
* This PR does not create a new version of the esri-loader library.

SDK Rename

---

README.md

This PR updates the README for Maps SDK capabilities that were removed at 4.27.
Closes https://github.com/Esri/esri-loader/issues/307.

chore(readme): update AMD async/await  known limitation
