Esri/esri-loader

- README.md
- index.ts
Load V4.2 by default
Use HTTPS by default
Resolves #3
> bump default version

- README.md
- index.ts
also add info to README on loading CSS
> default to version 4.3 of the ArcGIS API

- karma.conf.js
- package.json
- src/esri-loader.ts
- test/.travis.yml
- test/esri-loader.spec.js
tests are running on build output
update build and start tasks accordingly
resolves #18
> added unit tests, fixed no callback bug

- .gitignore
- karma.conf.js
- package.json
- rollup.config.js
moved build output under dist folder now b/c there are mulitple files
> add a minified build and source maps for published releases

- README.md
- package.json
- src/esri-loader.ts
README boilerplate
Find and replace on github.com/tomwayson/ w/ github.com/Esri/
Add copyright info to the top of source files
resolves #24
> prep for transfer to Esri org

- README.md
- src/esri-loader.ts
- test/esri-loader.spec.js
Updating references of ArcGIS API version 3 to 3.22
> Updating default to version 4.5 of the ArcGIS API

- README.md
The semicolon in the options object is invalid and was causing compile errors in my project. Removing it to save the next person from that error.
> fixed pre-loading sample

- .travis.yml
- CHANGELOG.md
- karma.conf.js
- package.json
> no longer running tests in phantom

- CHANGELOG.md
- scripts/release.sh
> add release script

- .gitignore
- CHANGELOG.md
- karma.conf.js
- package.json
- rollup.config.js
- tsconfig.json
> output esm and .d.ts to dist folder, only include dist/src when publishing

- README.md
- src/esri-loader.ts
- test/esri-loader.spec.js
Updating references of ArcGIS API version 3 to 3.23
> Updating default to version 4.6 of the ArcGIS API

- CHANGELOG.md
- src/esri-loader.ts
> make getScript() a public API

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- CHANGELOG.md
- package.json
Using FF in CI b/c of the failures in #73. Merging this instead b/c it's green.
resolves #58
> fuckit, let's test w/ FF in CI

- README.md
i haven't looked at this in awhile. the project is lookin ✨ 💯 !
> fix license 404 and bump badges up a bit

- CHANGELOG.md
- README.md
- added Choo and Riot examples to README
- n/a
> added Choo and Riot examples to README

- CHANGELOG.md
- README.md
- added Hyperapp example link to README
- Relates to Parcel curiosity in #72.  I'm a fan of Parcel now.
> added Hyperapp example link to README

- CHANGELOG.md
- src/esri-loader.ts
- src/utils/css.ts
> move CSS functions into own module

- README.md
Simple README update to replace old Angular CLI repo link (now archived) with a reference to the new Angular CLI repo: https://github.com/Esri/angular-cli-esri-map
> Update angular cli example app reference

- README.md
- adds Stencil example to README
- n/a
> adds stencil example application to readme

- .vscode/settings.json
- CHANGELOG.md
- README.md
- package.json
- src/esri-loader.ts
- test/esri-loader.spec.js
API Version update plus increment package version to 2.4.0 and removal of .vscode settings.
All in separate commits in case one doesn't suit!
D 
#120
> Update to API v4.8 & v3.25

- README.md
- src/esri-loader.ts
- test/esri-loader.spec.js
Updated all code & Readme to ArcGIS JavaScript API v4.9 & v3.26
> Updated all code & Readme to ArcGIS JavaScript API v4.9 & v3.26

- README.md
As described in #137, added a TOC. Tested that all hyperlinks work
> added a table of contents to README.md

- CHANGELOG.md
- src/esri-loader.ts
- src/utils/css.ts
- test/esri-loader.spec.js
resolves #107 
- Is there an example or test page to demonstrate any new or changed features?
nope
- Does your PR include appropriate tests for source code alterations?
yes
- If you're adding or changing a public API, did you update the docs Usage sections of the README? If not, please provide a code snippet that demonstrates how to consume the new or updated API(s).
nope
resolves #107
> add option to insert CSS link before an existing link tag

- README.md
update Dojo2 and React examples
n/a
> update Dojo2 and React examples

- README.md
> update readme w/ info vs webpack plugin and clean up a few things

- README.md
- updated readme to add info about using import types
https://github.com/Esri/esri-loader/issues/119
> Added info about using import types [issue 119]

- README.md
- src/script.test.ts
- src/utils/css.test.ts
- src/utils/url.test.ts
- src/utils/url.ts
Updated all code & Readme to latest version of ArcGIS JavaScript API
> Updated all code & Readme to ArcGIS JavaScript API v4.11 & v3.28

- src/script.test.ts
- src/utils/css.test.ts
- src/utils/url.test.ts
- src/utils/url.ts
Updated all code & Readme to ArcGIS JavaScript API v4.12 & v3.29
> Updated all code & Readme to ArcGIS JavaScript API v4.12 & v3.29

- README.md
API Version 3 documentation update
> API Version 3 update

- README.md
- src/utils/css.test.ts
- src/utils/url.test.ts
- src/utils/url.ts
> default to light css theme on 4.x

- README.md
- src/script.test.ts
- src/utils/css.test.ts
- src/utils/url.test.ts
- src/utils/url.ts
Updated all code & Readme to ArcGIS JavaScript API v4.13 & v3.30
> Updated all code & Readme to ArcGIS JavaScript API v4.13 & v3.30

- README.md
- Added a new Svelte example to the README
> Updated README with a new Svelte demo repo

- README.md
> link to esri-loader-hooks

- CHANGELOG.md
- README.md
- src/script.test.ts
- src/utils/css.test.ts
- src/utils/url.test.ts
- src/utils/url.ts
- Upgraded default versions to 3.34 & 4.17
> Upgrade to 3.34 & 4.17

- README.md
- src/script.test.ts
- src/script.ts
> remove option to set dojoConfig

- README.md
- src/script.test.ts
- src/utils/css.test.ts
- src/utils/url.test.ts
- src/utils/url.ts
> Update ArcGIS API for JavaScript version references (v4.18 and v3.35)

- CHANGELOG.md
- README.md
- src/script.test.ts
- src/utils/css.test.ts
- src/utils/url.test.ts
- src/utils/url.ts
> default to ArcGIS API for JavaScript version 4.20

- README.md
- src/script.test.ts
- src/utils/css.test.ts
- src/utils/url.test.ts
- src/utils/url.ts
> default to ArcGIS API for JavaScript version 4.21

- README.md
This PR only updates the Known Limitations section in the README.
> Update Angular zone.js compatibility deprecation notice
